# Generated by Django 5.1.3 on 2024-12-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('members', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='counter',
        ),
    ]
